### ISSUE TITLE
fail build with VS API4

### ISSUE THREAD

**Issue by sl1pkn07** [Jaded-Encoding-Thaumaturgy/vapoursynth-complexpr#1]
https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-complexpr/blob/eba0d99038bc511e133938a5b5b85ee35c2c31e3/exprdebug.cpp#L88

seems need change to `VSPresetVideoFormat`

greetings

**Comment by Setsugennoao** [comment]
Will fix, but it's not APIv4, just the last few versions
https://github.com/vapoursynth/vapoursynth/commit/b380a5898821734aea379bfe115e1300dc8230c8
